POST http://localhost:8000/api/order/create
Content-Type: application/json

{
    "listingId": "666028e7-b941-4205-9801-a94ceb09e865",
    "colorId": "85a55d66-2e58-4553-baf2-fb094eaac273",
    "size": "M",
    "customerEmail": "john.doe@example.com",
    "customerName": "John Doe",
    "shippingAddress": {
        "street": "123 Main St",
        "city": "New York",
        "state": "NY",
        "postalCode": "10001",
        "country": "USA",
        "phoneNumber": "+1234567890"
    }
}

// Get user orders api
GET http://localhost:8000/api/order/user
